
#====================================注意：系统属性添加处==============================
server:
  port: 8080
  servlet:
    path: /skss

#spring
spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.96.91.74:3306/my_sbm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: 123
          initial-size: 1
          min-idle: 1
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    mvc:
          static-path-pattern: /**
    resources:
#          static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/pic
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:C:/home/pic
    #redis配置
    redis:
      hostName: 47.96.91.74
      port: 6379
      password: 123
      #超时
      timeout: 10000ms
      #最大空闲数
      maxIdle: 300
      #控制一个pool可分配多少个jedis实例
      maxTotal: 1000
      #最大建立连接等待时间。
      maxWaitMillis: 1000
      #连接的最小空闲时间 默认1800000毫秒(30分钟)
      minEvictableIdleTimeMillis: 300000
      #每次释放连接的最大数目,默认3
      numTestsPerEvictionRun: 1024
      #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
      timeBetweenEvictionRunsMillis: 30000
      #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      testOnBorrow: true
      #在空闲时检查有效性, 默认false
      testWhileIdle: true

#mybatis
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.sbm.mapper
debug: true



#================================================自定义属性分割线（系统属性请勿在下添加）==================================
login:
      #sid
      accountSid : "ede863a6937e46628e5efaafe437633c"
      #模版内容
      smsContent : "您的验证码为{1}，请于{2}分钟内正确输入，如非本人操作，请忽略此短信。"
      #模版ID
      templateid : "285592961"
      #授权信息
      authToken : "28ac003c3a3040e9aa1c88a09f7e76d0"
      #准备url
      url : "https://api.miaodiyun.com/20150822/industrySMS/sendSMS"
      #缓存时间
      minute: 50


hello:
      defaultEncoding: "utf-8"
      maxUploadSize: "50000000"
      excludeUrls: "uploadPic.do"
